# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96d5afdbc3042c4ed9942fa535b0b60421da92f8044e94d4e06a840a3a0e99daf7d59f9f03ffd6291de6ad674ad8c626cc32b34681cbab7cbb60c29fe6520ec8

test:
  secret_key_base: 1540e26ebf956999ab07cec4650c7e97213b647122c496fa1b1c39c98f2ef3612e9afee0deaf52d4e0d8df2eab982ae8ca307eb2d1db4726f9dbba53f68bc54d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
